# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Carp-Fatals
version:      0.01
version_from: 
installdirs:  site
requires:
    CGI::Carp:                     0
    HTML::Perlinfo:                1.58

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
